---
kind: pipeline
name: build

clone:
  depth: 5000

steps:
  - name: build
    image: livingdocs/docker-node:20.10
    volumes:
      - name: dockersocket
        path: /var/run/docker.sock
    settings:
      push: true
      repo: livingdocs/docs
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD

  - name: release
    image: livingdocs/semantic-release:v2.1.1
    environment:
      GH_TOKEN:
        from_secret: GH_TOKEN

volumes:
  - name: dockersocket
    host:
      path: /var/run/docker.sock

trigger:
  event: [push]

---
kind: pipeline
name: tag

steps:
  - name: tag
    image: livingdocs/docker-node:20.10
    environment:
      DOCKER_USERNAME:
        from_secret: DOCKER_USERNAME
      DOCKER_PASSWORD:
        from_secret: DOCKER_PASSWORD
    commands:
      - |
        docker-login
        SHA_TAG=livingdocs/docs:sha-$DRONE_COMMIT_SHA
        RELEASE_TAG=livingdocs/docs:$DRONE_TAG
        regctl image cp $SHA_TAG $RELEASE_TAG

trigger:
  event: [tag]

---
kind: signature
hmac: 0231cb8f4527ace551e9aba128384e49eb769c91c6521f6f4e3073b828398eec

...
