---
kind: pipeline
name: build

clone:
  depth: 5000

steps:
  - name: build
    image: livingdocs/docker-node:28-22
    volumes:
      - name: dockersocket
        path: /var/run/docker.sock
    settings:
      push: true
      repo: livingdocs/docs
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD

  - name: release
    image: livingdocs/semantic-release:v3.0.3
    environment:
      GH_TOKEN:
        from_secret: GH_TOKEN

volumes:
  - name: dockersocket
    host:
      path: /var/run/docker.sock

trigger:
  event: [push]

---
kind: pipeline
name: tag

steps:
  - name: tag
    image: livingdocs/docker-node:28-22
    environment:
      DOCKER_USERNAME:
        from_secret: DOCKER_USERNAME
      DOCKER_PASSWORD:
        from_secret: DOCKER_PASSWORD
    commands:
      - |
        docker-login
        SHA_TAG=livingdocs/docs:sha-$DRONE_COMMIT_SHA
        RELEASE_TAG=livingdocs/docs:$DRONE_TAG
        regctl image cp $SHA_TAG $RELEASE_TAG

trigger:
  event: [tag]

---
kind: signature
hmac: 14b59a09279d47928fb83dedfe6de5ace7e75f64e14ad53f5e9bbe0e8ce53640

...
