---
kind: pipeline
name: build

clone:
  depth: 5000

steps:
- name: docker
  image: plugins/docker
  settings:
    repo: livingdocs/docs
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    tags: ["sha-${DRONE_COMMIT_SHA}"]

- name: release
  image: livingdocs/semantic-release:v1.0.0
  environment:
    GH_TOKEN:
      from_secret: GH_TOKEN

trigger:
  event: [push]

---
kind: pipeline
name: tag

steps:
- name: tag
  image: livingdocs/docker-node
  volumes:
    - name: dockersocket
      path: /var/run/docker.sock
  environment:
    DOCKER_USERNAME:
      from_secret: DOCKER_USERNAME
    DOCKER_PASSWORD:
      from_secret: DOCKER_PASSWORD
  commands:
    - |
      echo $DOCKER_PASSWORD | docker login -u="$DOCKER_USERNAME" --password-stdin 1>/dev/null
      SHA_TAG=livingdocs/docs:sha-$DRONE_COMMIT_SHA
      RELEASE_TAG=livingdocs/docs:$DRONE_TAG

      docker build -t $RELEASE_TAG . -f-<<EOF
      FROM $SHA_TAG
      EOF

      docker push $RELEASE_TAG

- name: deploy
  image: dtzar/helm-kubectl:3
  environment:
    KUBE_CONFIG:
      from_secret: kube_config
  commands:
    - |
      mkdir -p /root/.kube && echo "$KUBE_CONFIG" > /root/.kube/config && chmod 600 /root/.kube/config
      helm upgrade docs -n docs-prod --set "image.tag=${DRONE_TAG}" ./helm

volumes:
- name: dockersocket
  host:
    path: /var/run/docker.sock

trigger:
  event: [tag]

---
kind: signature
hmac: 2fe81489955c06e1e2c06499e5d894e73a93a4cf53ddc70f2d4e470255f325af

...
