title: Get Project Configuration

deprecation:
  since: release-2023-03
  note: Use `GET api/v1/projectConfig` instead.

scopes: public-api:read
query: |
  ACCESS_TOKEN=ey1234
  curl -k -X GET "https://server.livingdocs.io/api/v1/project" \
    -H "Authorization: Bearer $ACCESS_TOKEN"
endpoint:
  method: GET
  path: /api/v1/project
deprecated: release-2023-03
responses:
  - code: '200'
    body: |
      {
        "projectId": 1,
        "name": "b5c5f804-7927-44e2-a3fd-f97bc6784dab",
        "label": "Daily Planet",
        "defaultChannelId": 1,
        "channels": [
          {
            "channelId": 1,
            "channelHandle": "web",
            "label": "Web",
            "designName": "timeline",
            "designVersion": "1.1.0",
            "editMode": "default",
            "contentTypeHandles": [
              "regular",
              "page"
            ],
            "contentTypes": [
              {
                "contentTypeHandle": "regular",
                "documentType": "article",
                "metadata": [
                  {
                    "name": "title",
                    "plugin": "li-text"
                  },
                  {
                    "name": "author",
                    "plugin": "li-text"
                  },
                  {
                    "name": "teaserImage",
                    "plugin": "li-image"
                  },
                  {
                    "name": "dependencies",
                    "plugin": "li-dependencies"
                  },
                  {
                    "name": "tasks",
                    "plugin": "li-tasks"
                  }
                ],
                "renditionHandles": [
                  "web",
                  "mobile"
                ]
              },
              {
                "contentTypeHandle": "page",
                "documentType": "page",
                "metadata": [
                  {
                    "name": "title",
                    "plugin": "li-text"
                  },
                  {
                    "name": "dependencies",
                    "plugin": "li-dependencies"
                  },
                  {
                    "name": "routing",
                    "plugin": "li-default-routing"
                  }
                ],
                "renditionHandles": [
                  "web"
                ]
              }
            ]
          }
        ]
      }
