title: Get Design Configuration
useCases: |
  - Load the appropriate Design Version for a document

scopes: public-api:read
query: |
  ACCESS_TOKEN=ey1234
  curl -k -X GET "https://server.livingdocs.io/api/v1/design/:designVersion" \
    -H "Authorization: Bearer $ACCESS_TOKEN"
endpoint:
  method: GET
  path: /api/v1/design/:designVersion
parameters:
  - name: :designVersion
    type: string
    required: false
    notes: 'Optional design version. Will take the current design version of a channel if none is passed.'
responses:
  - code: '200'
    body: |
      {
        "name": "p:1:1",
        "version": "1.0.0",
        "assets": {
          "css": [
            "https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"
          ]
        },
        "defaultComponents": {
          "paragraph": "p",
          "image": "image"
        },
        "groups": [
          {
            "name": "content",
            "label": "Components",
            "components": [
              "title",
              "p",
              "image",
              "insta"
            ]
          }
        ],
        "componentProperties": {},
        "metadata": [
          {
            "identifier": "title",
            "type": "text",
            "matches": [
              "title.title"
            ]
          }
        ],
        "components": [
          {
            "name": "title",
            "label": "Title",
            "iconUrl": "https://livingdocs-assets.s3.amazonaws.com/magazine-design/assets/images/icons-components/icon_header_simple.svg",
            "html": "<h2 doc-editable=\"title\">\n  Title\n</h2>",
            "directives": {}
          },
          {
            "name": "p",
            "label": "Paragraph",
            "iconUrl": "https://livingdocs-assets.s3.amazonaws.com/magazine-design/assets/images/icons-components/icon_text.svg",
            "html": "<p class=\"text\" doc-editable=\"text\">\n  Paragraph\n</p>",
            "directives": {}
          },
          {
            "name": "image",
            "label": "Image",
            "iconUrl": "https://livingdocs-assets.s3.amazonaws.com/magazine-design/assets/images/icons-components/icon_image.svg",
            "directives": {
              "img": {
                "name": "img",
                "type": "image",
                "imageRatios": [
                  "16:9",
                  "1:1",
                  "4:3",
                  "3:4"
                ]
              }
            },
            "html": "<img\n  doc-image=\"img\"\n  class=\"responsive-img\">"
          },
          {
            "name": "insta",
            "label": "Instagram",
            "iconUrl": "https://livingdocs-assets.s3.amazonaws.com/magazine-design/assets/images/icons-components/icon_image.svg",
            "directives": {
              "insta": {
                "name": "insta",
                "type": "include",
                "service": "instagram"
              }
            },
            "html": "<div doc-include=\"insta\">\n  <div>Instagram Include</div>\n</div>"
          }
        ]
      }
